### ISSUE TITLE
Hows new version?

### ISSUE THREAD

**Issue by Umity** [adrianopaladini/Live-blurView#2]
Hi, this is not an issue with the module but just a question. I saw in the main page that you are working on a new improved version. Hows going? I am using your module on my app and would like to use the upcoming one because it looks amazing.

**Comment by adrianopaladini** [comment]
Sorry, but i will not release a new version too early, because i can not do it work without use of private Apple API. This use make any app that use this module will not aproved on AppStore.
If one day i make it work like i do using Private API bit without this, i will commit here.

**Comment by Umity** [comment]
it seems like Apple allowing  this now...?

**Comment by adrianopaladini** [comment]
With the upcoming iOS 8, Apple released a new API for this feature. 
I'll make a new module with this change, but only after the release of iOS 8 GM. 
But keep in mind that this is only for iOS 8 or higher. 
Reference:
https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIBlurEffect_Ref/index.html

**Comment by Umity** [comment]
Thank you very much Adriano :)

**Comment by bcpi** [comment]
Thank you Adriano. I look forward to the updated release as well.

**Comment by adrianopaladini** [comment]
New version released!
